### ISSUE TITLE
extract-bc on Mac

### ISSUE THREAD

**Issue by BrunoDutertre** [SRI-CSL/whole-program-llvm#15]
Downloaded the latest Xcode today. It comes with a new version of otool that
does not respect the -X flag. As a result, extract-bc does not work anymore 
for me.

**Comment by ianamason** [comment]
This looks to be a bug in otool, since it claims -X  will  "print no leading addresses or headers".
That said I could provide a better  parser that will handle this. First I need to get the old otool
working so I can compare...

Thanks for diagnosing this.

**Comment by ianamason** [comment]
Fixed by throwing away any lines of output from otool that isn't whitespace and hex.
