### ISSUE TITLE
-emit-llvm 

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/whole-program-llvm#18]
Write a simple example that uses -emit-llvm to compile a bunch of .c's into .bc's
then links them into a exe either by way of intermediate .o's or directly, and see 
if we can handle it correctly.

**Comment by ianamason** [comment]
Just waiting now for some stress tests. Perhaps by @relentless-warrior

**Comment by relentless-warrior** [comment]
@ianamason: Overwhelmed with another project until tomorrow evening. I will try it tomorrow (Friday) night and let you know.

**Comment by ianamason** [comment]
no problem @relentless-warrior, just wanted you to know that there is something there for you 
to test if so inclined.

**Comment by ianamason** [comment]
We should also see if we have fixed  the issues Marko @mdimjasevic was having. 


https://dimjasevic.net/marko/2015/11/09/getting-llvm-bitcode-with-clang-from-android-take-ii/

**Comment by mdimjasevic** [comment]
That was quite a while ago and I believe with the original version of WLLVM. In the meantime I moved onto other projects, i.e. I'm not working with WLLVM anymore.

**Comment by relentless-warrior** [comment]
@ianamason: wllvm works correctly for a couple of .c files. Here is the Makefile that I have used for my testing:
```
##################################
CC = wllvm
all: hello
hello: a.o b.o
	$(CC) a.o b.o -o hello
a.o: a.c
	$(CC) -c a.c
b.o: b.c
	$(CC) -c b.c
clean:
	rm -f *o hello
####################################
```
I have then used the extract-bc script to extract the .bc from the hello exe file.

**Comment by ianamason** [comment]
Yes I have a whole bunch of tests like that  in my fork. I was hoping you 
were going to build the bluetooth library. See if that works :-)

**Comment by ianamason** [comment]
Fixed but not tested on anything other than toy examples.
