### ISSUE TITLE
store feature 

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/whole-program-llvm#21]
does not work for python 3.3 3.4 or 3.5 but only for 2.7

maybe the copy file library?  I will write a simple test
tomorrow so we can figure out why @loicgelle

**Comment by loicgelle** [comment]
@ianamason I can see that you are investigating. Any leads?

**Comment by ianamason** [comment]
@loicgelle 

yes: unicode-objects must be encoded before hashing hashlib

thus I inserted a .encode()
