### ISSUE TITLE
Version 1.2.4 is broken on pypi

### ISSUE THREAD

**Issue by futile** [SRI-CSL/whole-program-llvm#24]
Pipenv currently fails for me when installing wllvm in version 1.2.4. From the corresponding filelist on pypi.org (https://pypi.org/project/wllvm/1.2.4/#files) I saw that something seems to be missing, i.e., there is no `wllvm-1.2.4.tar.gz` available. https://pypi.org/simple/wllvm/ also does not list a `wllvm-1.2.4.tar.gz`. Is this just a temporary bug (caches somewhere?) or is something actually broken?

**Comment by ianamason** [comment]
Well I moved to twine from 1.2.3 to 1.2.4 so it is quite probable that I broke something.
Let me scratch around a bit.

**Comment by ianamason** [comment]
OK, @futile,  maybe 1.2.5 will work for you? Wanna try it and get back to me?

**Comment by futile** [comment]
Version 1.2.5 is working again! Thanks a lot for the quick fix @ianamason! :) I don't know much about versioning with pypi, but maybe (if possible) it might make sense to retract/unpublisch version 1.2.4, since it probably won't work for others either. From my side the issue is definitely fixed and can be closed!

**Comment by ianamason** [comment]
1.2.3 and 1.2.4 have gone the way of the dodo and thylacine.  Thanks @futile for reporting the issue.
