### ISSUE TITLE
bzip2 make all fail

### ISSUE THREAD

**Issue by aaltinay** [SRI-CSL/whole-program-llvm#26]
Line 37 of Makefile in bzip2, clang should be gclang I think. It fails otherwise.

**Comment by ianamason** [comment]
There is a patch no?

**Comment by aaltinay** [comment]
Looks like I open the issue to wllvm instead of gllvm, my bad :D
The patch looks like to replace CC. This is for the other Makefile:
src/github.com/SRI-CSL/gllvm/examples/bzip2/Makefile

**Comment by ianamason** [comment]
Ok I will take a look tomorrow.

**Comment by ianamason** [comment]
No that just the linking step on the produced bitcode.  It can be clang or clang++ with no issues.

**Comment by aaltinay** [comment]
Yes but if clang is not on the $PATH, it will not find clang. That was the case for me. I am not really familiar with the project but we set environment variables like LLVM_COMPILER or LLVM_COMPILER_PATH to tell gllvm/wllvm where is the compiler and I believe gllvm/wllvm uses these env variables to find the right compiler. So I changed clang to gllvm and it fixed compilation error.

**Comment by ianamason** [comment]
Yes I suppose that’s true. You’ll excuse me if I don’t let perfect be the enemy of good.

**Comment by ianamason** [comment]
Fixed by [this](https://github.com/SRI-CSL/gllvm/commit/502ac0f05f5731f6d739e5c9a24f699d40b4bb1c) over at [gllvm](https://github.com/SRI-CSL/gllvm)
