### ISSUE TITLE
extract-bc mangles paths on Apple Silicon

### ISSUE THREAD

**Issue by carlocab** [SRI-CSL/whole-program-llvm#29]
I submitted wllvm for packaging in Homebrew at https://github.com/Homebrew/homebrew-core/pull/72115.

While testing the install, the ARM node encountered an [error](https://github.com/Homebrew/homebrew-core/pull/72115/checks?check_run_id=2074499916#step:7:76) reminiscent of #28:

```
==> /opt/homebrew/Cellar/wllvm/1.3.0/bin/wllvm /private/tmp/wllvm-test-20210309-48266-1km22w6/test.c -o /private/tmp/wllvm-test-20210309-48266-1km22w6/test
==> /opt/homebrew/Cellar/wllvm/1.3.0/bin/extract-bc /private/tmp/wllvm-test-20210309-48266-1km22w6/test
llvm-link: irp/etavpmt/llw/t-mv-tse12029030284-1-6622mk./6wtsetb.o.c: error: Could not open input file: No such file or directory
llvm-link: error:  loading file 'irp/etavpmt/llw/t-mv-tse12029030284-1-6622mk./6wtsetb.o.c'
```

Indeed, everything should be as what I reported there, but for the processor.

I don't personally have access to a machine on Apple Silicon, so I'm afraid I won't be very helpful debugging this one. However, I thought it would be useful for you to know.

**Comment by ianamason** [comment]
Sigh. I will have to think. My guess is that otool on Apple Silicon has yet another behaviour?

**Comment by carlocab** [comment]
I wasn't aware that it did, but it certainly looks like it. I'll try to see if I know someone who'll lend me some time on their machine to try to generate some debug logs as in #28.

**Comment by ianamason** [comment]
Maybe the time has come to look at [this](https://pypi.org/project/lief/)

**Comment by ianamason** [comment]
I'm looking around for an Apple Silicon device.  Is it possible just to put a call to otool in the homebrew tests?
Something like:
```
otool -X -s __WLLVM __llvm_bc test
```

**Comment by carlocab** [comment]
It's possible, but the CI setup isn't really configured for debugging, so getting it to display things that aren't error messages requires a bit of additional work. So, say, running 
```
otool -X -s __WLLVM __llvm_bc test
```
will typically display nothing if it returns an exit code of `0`. We can probably capture the output, put it in a variable, and then explicitly say we want to print the contents of that variable.

**Comment by ianamason** [comment]
Oh well, just an idea. I guess my lab will eventually get some Apple Silicon devices, but if I order
one it will arrive tectonically. Eventually we will solve it.

**Comment by ianamason** [comment]
OK so I put in an order for one. The race is on.

**Comment by ianamason** [comment]
@carlocab  I am writing this on an M1. 
I can reproduce the issue.
Should have a fix soon.

**Comment by ianamason** [comment]
As I guessed, `otool` is the villian.  On my m1 I see:
```
iam@Ians-MBP test_files % otool -X -s __WLLVM __llvm_bc main
000000010000c000	6573552f 692f7372 522f6d61 736f7065
000000010000c010	726f7469 2f736569 48746947 532f6275
000000010000c020	432d4952 772f4c53 656c6f68 6f72702d
000000010000c030	6d617267 766c6c2d 65742f6d 742f7473
000000010000c040	5f747365 656c6966 662e2f73 6f2e6f6f
000000010000c050	0a63622e 6573552f 692f7372 522f6d61
000000010000c060	736f7065 726f7469 2f736569 48746947
000000010000c070	532f6275 432d4952 772f4c53 656c6f68
000000010000c080	6f72702d 6d617267 766c6c2d 65742f6d
000000010000c090	742f7473 5f747365 656c6966 622e2f73
000000010000c0a0	6f2e7261 0a63622e 6573552f 692f7372
000000010000c0b0	522f6d61 736f7065 726f7469 2f736569
000000010000c0c0	48746947 532f6275 432d4952 772f4c53
000000010000c0d0	656c6f68 6f72702d 6d617267 766c6c2d
000000010000c0e0	65742f6d 742f7473 5f747365 656c6966
000000010000c0f0	622e2f73 6f2e7a61 0a63622e 6573552f
000000010000c100	692f7372 522f6d61 736f7065 726f7469
000000010000c110	2f736569 48746947 532f6275 432d4952
000000010000c120	772f4c53 656c6f68 6f72702d 6d617267
000000010000c130	766c6c2d 65742f6d 742f7473 5f747365
000000010000c140	656c6966 6d2e2f73 2e6e6961 63622e6f
000000010000c150	0a
```
which clearly needs to be parsed in a different fashion.

**Comment by ianamason** [comment]
9f2b34d2ce6c394c656cf99498453175d3aab9ff  should fix this. Wanna try it out @carlocab

**Comment by carlocab** [comment]
Tried it out. Works great; thanks very much!

Do you plan on updating the version on PyPI with this?

**Comment by ianamason** [comment]
Yes I will cut a new version this weekend I guess. I will ping you, maybe you can try the homebrew thing again with it?

**Comment by ianamason** [comment]
The new [version](https://pypi.org/project/wllvm/1.3.1/) is live @carlocab

**Comment by carlocab** [comment]
Thanks very much, @ianamason.
