### ISSUE TITLE
how to use wllvm to compile firefox?

### ISSUE THREAD

**Issue by Frankenstein-bit** [SRI-CSL/whole-program-llvm#30]
firefox do not give a configure file. How should i compile firefox use wllvm

**Comment by ianamason** [comment]
Isn't firefox written in rust?

**Comment by Frankenstein-bit** [comment]
> Isn't firefox written in rust?

rust only accounts for a small part of firefox, and c\c++ accounts for the vast majority

**Comment by ianamason** [comment]
Well it should be possible. I'm not going to try though. First see if you can build it with clang. You should be able to google that. Then the rest should be straightforward.

**Comment by Frankenstein-bit** [comment]
> 

thank you very much
